name: CI/CD to Render 
 
on: 
  release: 
    types: [created] 
 
jobs: 
  test: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Repository auschecken 
        uses: actions/checkout@v4 
 
      - name: Node.js einrichten 
        uses: actions/setup-node@v4 
        with: 
          node-version: 18 
          cache: 'npm' 
 
      - name: Abhängigkeiten installieren 
        run: npm install 
 
      - name: Tests ausführen 
        run: npm test 
 
  deploy: 
    needs: test 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Repository auschecken 
        uses: actions/checkout@v4 
 
      - name: Deployment auf Render auslösen 
        run: | 
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
